version: '3'
services:
  backend:
    build: ./portfolio_backend
    volumes:
      - ./portfolio_backend:/app
    ports:
      - '8000:8000'
  frontend:
    build: ./portfolio_frontend
    volumes:
      - ./portfolio_frontend:/app
    ports:
      - '5173:5173'
    environment:
      - PORT=5173
